const MessageType = {
  QUERY_LATEST: 0,
  QUERY_ALL: 1,
  RESPONSE_BLOCKCHAIN: 2,
  QUERY_TRANSACTION_POOL: 3,
  RESPONSE_TRANSACTION_POOL: 4,
  QUERY_NODES: 5,
  RESPONSE_NODES: 6,
  NODE_ADDRESS: 7
};

module.exports = {
  MessageType
};

