name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14, 16 ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: server
        run: yarn install --frozen-lockfile

      - name: Run tests
        working-directory: server
        run: yarn test --detectOpenHandles

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          to: kptankhoa@gmail.com
          from: Khoa Phan
          secure: true
          body: Build job of ${{github.repository}} completed successfully!
#          cc: kyloren@example.com,leia@example.com
          ignore_cert: true
          priority: high

#      - run: npm run build --if-present
